### ISSUE TITLE
add plugin "settings" to the boilerplate

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable-Extension-Boilerplate#1]
Would be great if there were some settings in the boilerplate in case we wanted to have settings appear next to General, Payment Gateways, Emails, etc.

**Comment by ericnicolaas** [comment]
This was added in f4657d44eb91905623b053a6787b38da76e99340

Note however that in order for this to work, you need the bleeding edge version of Charitable as well. It will work with 1.3+.

**Comment by helgatheviking** [comment]
:+1:
